[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Callum Ward <wards.callum@gmail.com>"]
edition = "2018"
default-run="07"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
